---
extends: default
rules:
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  line-length:
    max: 120
    level: warning
  # don't bother me with this rule
  indentation: disable
